
import java.awt.BorderLayout;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dwk5369
 */
public class SchedulerMenu extends javax.swing.JFrame {

    ScheduleView jpSchedule;
    RAPView jpRAP;
    ConflictView jpConflict;
    ClassScheduler cs;
    String semesterName;
    String semesterYear;
    
    /**
     * Creates new form SchedulerMenu
     */
    public SchedulerMenu() {
        initComponents();
        cs = new ClassScheduler();
        jpSchedule = new ScheduleView();
        jpRAP = new RAPView();
        jpConflict = new ConflictView();
        this.setLayout(new BorderLayout());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpWelcome = new javax.swing.JPanel();
        jbBegin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiQuit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiScheduleView = new javax.swing.JMenuItem();
        jmiRAPView = new javax.swing.JMenuItem();
        jmiConflictView = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbBegin.setText("Begin");
        jbBegin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBeginActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Welcome to the eRegistrar Class Scheduler!");

        jLabel2.setText("To start scheduling, click the button below!");

        jLabel3.setText("To load a schedule from a previous semester, use File>Load");

        javax.swing.GroupLayout jpWelcomeLayout = new javax.swing.GroupLayout(jpWelcome);
        jpWelcome.setLayout(jpWelcomeLayout);
        jpWelcomeLayout.setHorizontalGroup(
            jpWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpWelcomeLayout.createSequentialGroup()
                .addGroup(jpWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpWelcomeLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel2))
                    .addGroup(jpWelcomeLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jpWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpWelcomeLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jbBegin)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jpWelcomeLayout.setVerticalGroup(
            jpWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpWelcomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbBegin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jmiQuit.setText("Quit");
        jmiQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiQuitActionPerformed(evt);
            }
        });
        jMenu1.add(jmiQuit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Scedule");
        jMenu2.setEnabled(false);

        jmiScheduleView.setText("Schedule View");
        jmiScheduleView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiScheduleViewActionPerformed(evt);
            }
        });
        jMenu2.add(jmiScheduleView);

        jmiRAPView.setText("RAP View");
        jmiRAPView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRAPViewActionPerformed(evt);
            }
        });
        jMenu2.add(jmiRAPView);

        jmiConflictView.setText("Conflict View");
        jmiConflictView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConflictViewActionPerformed(evt);
            }
        });
        jMenu2.add(jmiConflictView);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiScheduleViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiScheduleViewActionPerformed
        this.add(jpSchedule, BorderLayout.CENTER);
        this.remove(jpRAP);
        this.remove(jpConflict);
        //jpRAP.setVisible(false);
        this.remove(jpWelcome);
        jpSchedule.doSchedule();
        repaint();
        pack();
    }//GEN-LAST:event_jmiScheduleViewActionPerformed

    private void jmiRAPViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRAPViewActionPerformed
        this.add(jpRAP, BorderLayout.CENTER);
        this.remove(jpSchedule);
        this.remove(jpConflict);
        //jpSchedule.setVisible(false);
        this.remove(jpWelcome);
        jpRAP.setCS(cs);
        
        
        repaint();
        pack();
    }//GEN-LAST:event_jmiRAPViewActionPerformed

    private void jmiQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiQuitActionPerformed
        int intExit = JOptionPane.showConfirmDialog(this, "Are you sure you want to quit?", "Exit Scheduler", JOptionPane.YES_NO_OPTION);
        if(intExit == 0)
            System.exit(0);
    }//GEN-LAST:event_jmiQuitActionPerformed

    private void jbBeginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBeginActionPerformed
        cs.schedule();
        jpConflict.setCS(cs);
        jpSchedule.setCS(cs);
        jpRAP.setCS(cs);
        JOptionPane.showMessageDialog(this, "Conflicts were detected in the generated schedule.", "Scheduling Conflicts", JOptionPane.ERROR_MESSAGE);
        this.remove(jpWelcome);
        this.add(jpConflict);
        jMenu2.setEnabled(true);
        repaint();
        pack();
    }//GEN-LAST:event_jbBeginActionPerformed

    private void jmiConflictViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConflictViewActionPerformed
        this.add(jpConflict);
        this.remove(jpWelcome);
        this.remove(jpSchedule);
        this.remove(jpRAP);
        repaint();
        pack();
    }//GEN-LAST:event_jmiConflictViewActionPerformed


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SchedulerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SchedulerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SchedulerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchedulerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SchedulerMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton jbBegin;
    private javax.swing.JMenuItem jmiConflictView;
    private javax.swing.JMenuItem jmiQuit;
    private javax.swing.JMenuItem jmiRAPView;
    private javax.swing.JMenuItem jmiScheduleView;
    private javax.swing.JPanel jpWelcome;
    // End of variables declaration//GEN-END:variables
}
